USE ebana_stuffhub;

-- Add missing columns to users table if they don't exist
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS firstName VARCHAR(100),
  ADD COLUMN IF NOT EXISTS lastName VARCHAR(100),
  ADD COLUMN IF NOT EXISTS phone VARCHAR(30),
  ADD COLUMN IF NOT EXISTS role ENUM('employee','admin') DEFAULT 'employee',
  ADD COLUMN IF NOT EXISTS resetToken VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS resetTokenExpiry DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add missing columns to requests table if they don't exist
ALTER TABLE requests
  ADD COLUMN IF NOT EXISTS userId INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS name VARCHAR(100) NOT NULL DEFAULT 'Employee',
  ADD COLUMN IF NOT EXISTS email VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS type ENUM('vacation','suggestion','appeal','resignation') NOT NULL DEFAULT 'vacation',
  ADD COLUMN IF NOT EXISTS message TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `start` DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `end` DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS days INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS status ENUM('pending','approved','rejected') DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
